name: Bots

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: '@dependabot merge'

  cache:
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/cache.yml

  yarn-sdk:
    name: Rebuild Yarn SDKs
    runs-on: ubuntu-latest
    needs: [cache]
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.cache.outputs.yarn-cache-key }}
          path: ${{ needs.cache.outputs.yarn-cache-path }}

      - name: Update SDKs
        run: yarn dlx @yarnpkg/sdks

      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: yarn sdks'
