name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
